services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    command:
      python3 src/main.py
    networks:
      - local
    ports:
      - "8000:8000"

  redis:
    image: redis
    container_name: redis
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  redis: